### PR TITLE
[WIP] Addressing some of the goals #6. 

### PR DESCRIPTION
**Pull request by ghost**
# Change log
[ + ] Added comments 

*Do not merge.*

### CODE REVIEW

**Comment by ghost** [comment]
@ForceBru on line [220](https://github.com/MrHallway0/PyVM/blob/0f6e016bc6e946c3d013e2f42d0b05976f787146/VM/Registers.py#L220) of `Registers.py` shouldn't the error being raised be in an `else:` condition?

**Comment by ghost** [comment]
also `_pack_` could be a global variable because it is being set to 1 by every function anyway.

**Comment by ForceBru** [comment]
> @ForceBru on line [220](https://github.com/MrHallway0/PyVM/blob/0f6e016bc6e946c3d013e2f42d0b05976f787146/VM/Registers.py#L220) of `Registers.py` shouldn't the error being raised be in an `else:` condition?

Technically yes, but I'm returning from each `if/else` branch, so control can only reach the end of the function when none of the `if/else` branches were taken, so the `else` can safely be omitted.

**Comment by ForceBru** [comment]
> also `_pack_` could be a global variable because it is being set to 1 by every function anyway.

If you're talking about `_pack_`s like these:

https://github.com/ForceBru/PyVM/blob/cf1838ac4d94419ce10919b4bf83eeb484ad73fe/VM/Registers.py#L38-L39

https://github.com/ForceBru/PyVM/blob/cf1838ac4d94419ce10919b4bf83eeb484ad73fe/VM/Registers.py#L61-L62

Then they can't be global variables because they're class attributes. Also, they're only used internally by `ctypes` - none of my functions are updating them, AFAIK.

**Comment by ghost** [comment]
Okay, both of those answers make since.

**Comment by ghost** [comment]
Does line 29 in `CPU.py` define the cache size? 
https://github.com/ForceBru/PyVM/blob/cf1838ac4d94419ce10919b4bf83eeb484ad73fe/VM/CPU.py#L29

**Comment by ForceBru** [comment]
@BetaPictoris, this is used here and in similar scenarios to select operand size and address size:

https://github.com/ForceBru/PyVM/blob/cf1838ac4d94419ce10919b4bf83eeb484ad73fe/VM/CPU.py#L33-L35

This representation as a tuple of two values is useful because address size and operand size can only be one of two things: 4 bytes or 2 bytes, so one can index this tuple by a Boolean (0 or 1), as shown here:

https://github.com/ForceBru/PyVM/blob/cf1838ac4d94419ce10919b4bf83eeb484ad73fe/VM/fetchLoop.py#L93-L101

This CPU doesn't have a notion of cache at all: instructions are read one-by-one in a loop:

https://github.com/ForceBru/PyVM/blob/cf1838ac4d94419ce10919b4bf83eeb484ad73fe/VM/fetchLoop.py#L80-L82

...and fed straight into the parsing/execution machinery, which is described here: https://github.com/ForceBru/PyVM/blob/master/VM/instructions/README.md

**Pull request closed without merging**
